## 48 Rotate Image

### Brute Force Approach
Time Complexity: $$O(N^2)$$
Space Complexity: $$O(N^2)$$

In [32]:
import numpy as np
def display_matrix(matrix):
    print(np.matrix(matrix))

In [33]:
def rotate(matrix: list[list[int]]) -> None:
    temp_matrix = [[0]*len(matrix[0]) for idx in range(0, len(matrix))]
    n = len(matrix[0])
    
    for rowIdx in range(0, len(matrix)):
        for colIdx in range(0, len(matrix[0])):
            temp_matrix[colIdx][n-rowIdx-1] = matrix[rowIdx][colIdx]
    return temp_matrix

In [34]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]
display_matrix(matrix)
output = rotate(matrix)
print()
display_matrix(output)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[7 4 1]
 [8 5 2]
 [9 6 3]]


### Optimal Solution

1. Take transpose of matrix
2. Reverse every row inside the matrix.

In [35]:
def rotate(matrix: list[list[int]]) -> None:
    # transpose of matrix
    for rowIdx in range(0, len(matrix)):
        for colIdx in range(rowIdx, len(matrix[0])):
            temp = matrix[rowIdx][colIdx]
            matrix[rowIdx][colIdx] = matrix[colIdx][rowIdx]
            matrix[colIdx][rowIdx] = temp
    
    for listIdx in range(0, len(matrix)):
        matrix[listIdx][:] = matrix[listIdx][::-1] 

In [36]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]
display_matrix(matrix)
rotate(matrix)
print()
display_matrix(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[7 4 1]
 [8 5 2]
 [9 6 3]]
