## 54 Spiral Matrix

In [2]:
import numpy as np
def display_matrix(matrix):
    print(np.matrix(matrix))

In [59]:
def spiralOrder(matrix: list[list[int]]) -> None:
    top_row = left_col = 0
    bottom_row = len(matrix)-1
    right_col = len(matrix[0])-1
    print(top_row, bottom_row, left_col, right_col)

    for rowIdx in range(0, bottom_row//2+1):
        for colIdx in range(left_col, right_col+1):
            print(matrix[rowIdx][colIdx], end="-")
        
        for rowIdx2 in range(rowIdx+1, bottom_row+1):
            print(matrix[rowIdx2][right_col], end="-")
        for colIdx in range(right_col-1, left_col-1, -1):
            print(matrix[bottom_row][colIdx], end="-")
        for rowIdx2 in range(bottom_row-1, rowIdx, -1):
            print(matrix[rowIdx2][left_col], end="-")
        bottom_row -= 1
        left_col += 1
        right_col -= 1
        # break

In [60]:
matrix = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
display_matrix(matrix)
spiralOrder(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
0 2 0 3
1-2-3-4-8-12-11-10-9-5-6-7-6-

In [38]:
[i for i in range(10, -1, -1)]

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]