## 73 Set Matrix Zeroes

In [20]:
import numpy as np
def display_matrix(matrix: list[list[int]]) -> None:
    print(np.matrix(matrix))

In [16]:
# brute force solution
def setZeroes(matrix: list[list[int]]) -> None:
    """
    Do not return anything, modify matrix in-place instead.
    """
    n = len(matrix)     # no of rows
    m = len(matrix[0])  # no of cols
    rows = [0]*n
    cols = [0]*m

    for row in range(0, len(matrix)):
        for col in range(0, len(matrix[row])):
            if matrix[row][col] == 0:
                rows[row] = 1
                cols[col] = 1

    for rowIdx in range(0, len(rows)):
        for colIdx in range(0, len(cols)):
            if (rows[rowIdx] == 1) and (cols[colIdx] == 1):
                for col in range(0, m):
                    matrix[rowIdx][col] = 0
                for row in range(0, n):
                    matrix[row][colIdx] = 0                        

In [23]:
matrix = [[1,1,1],[1,0,1],[1,1,1]]
display_matrix(matrix)
print()
setZeroes(matrix)
print(np.matrix(matrix))

[[1 1 1]
 [1 0 1]
 [1 1 1]]

[[1 0 1]
 [0 0 0]
 [1 0 1]]


In [60]:
# optimal solution
def setZeroes(matrix) -> None:
    n = len(matrix)     # no. of rows
    m = len(matrix[0])  # no. of cols
    extra = 1
    for row in range(0, n):
        for col in range(0, m):
            if matrix[row][col] == 0:
                if (col == 0):
                    extra = 0
                else:
                    matrix[0][col] = 0
                    matrix[row][0] = 0


    print()
    display_matrix(matrix)
    print()

    for row in range(1, n):
        for col in range(1, m):
            if (matrix[0][col] == 0) or (matrix[row][0] == 0):
                matrix[row][col] = 0
    
    if matrix[0][0] == 0:
        for col in range(0, m):
            matrix[0][col] == 0
    if extra == 0:
        for row in range(0, n):
            matrix[row][0] = 0


In [61]:
matrix =[[1,1,1],[0,1,1],[1,1,1]]
display_matrix(matrix)
print()
setZeroes(matrix)
print(np.matrix(matrix))

[[1 1 1]
 [0 1 1]
 [1 1 1]]

extra:  0

[[1 1 1]
 [0 1 1]
 [1 1 1]]

[[0 1 1]
 [0 0 0]
 [0 1 1]]
